# Generated by Django 6.0.4 on 2026-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждён администратором'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('admin', 'Администратор'), ('receptionist', 'Приёмщик'), ('master', 'Мастер')], default='receptionist', max_length=50, verbose_name='Должность'),
        ),
    ]
